### PR TITLE
Doom VFR jet strafe

### PR DESCRIPTION
**Pull request by jckhng**
Added Doom VFR jet strafe locomotion mechanism into the Doom VFR (previously QuakeCon) teleport mode (under Comfort Options). Touch the top, bottom, left and right edge of the left touchpad to "jet strafe" immediately in that direction in a fixed step.

The jet strafe is described in this video: https://youtu.be/hhDbEaVQXJc?t=3m53s

The jet strafe implementation can be viewed at https://youtu.be/m1y1ATU0ysE

### CODE REVIEW

**Comment by KozGit** [comment]
Wow, nice work, thanks for adding this!  I'm in the middle of some local changes on v022. - as soon as I finish them, I will push then merge this.  It will probably be a little bit before I finish.  I'm on vacation next week  - but I definitely want to get these included asap.

**Comment by jckhng** [comment]
Just committed some fixes for jet strafe and teleport to work better.

**Comment by KozGit** [comment]
So, finally finished updating the model anims and am taking a look at this, but using Touch controls , the Jet Strafe does not appear to do anything.  I can teleport with the time slowdown and dash style teleport, but the left stick does nothing. Haven't tested with the Vive yet.

( And Just to make sure I'm not being dumb, how am I supposed to be using the controls for jet strafe and VFR style teleporting. Do you need to push the teleport button to strafe? )

**Comment by jckhng** [comment]
I have tested it out on the Vive and it was working fine. Unfortunately, I do not have a Rift to test on so I am not very familiar with the Touch controllers. I think it should be a new discrete tap for each jump rather than repeated jumps while held. 

Thank you for updating the model animations!

**Pull request merged**
