### PR TITLE
Added the QuakeCon style teleport. Time slows down when holding down …

### PR DESCRIPTION
**Pull request by jckhng**
…the teleport button, and darts over to the new position, once the button is released. The teleport mechanism is described in detail at http://www.gamespot.com/articles/doom-may-have-solved-vrs-traversal-problem/1100-6442439/.

vr_teleportMode can be set in console or in the VR Options menu.
0 - Blink (default)
1 - QuakeCon style

The QuakeCon style teleport can be viewed at https://youtu.be/pKKYWieDHJM

### CODE REVIEW

**Comment by CarlKenner** [comment]
Great!
BTW, how should we credit you? Currently you're credited as 
"jckhng:
    Slow Mo and Tunnel vision motion sickness fixes."

**Comment by CarlKenner** [comment]
Great!
BTW, how should we credit you? Currently you're credited as 
"jckhng:
    Slow Mo and Tunnel vision motion sickness fixes."

From the YouTube channel, I'm guessing that's short for Jack Huang.

**Comment by CarlKenner** [comment]
What is the "noclip problem"?
I don't like the falling at the end caused by adding 50 to the vertical velocity.

**Comment by jckhng** [comment]
There is an area near the beginning of the game after you exit to Mars surface to get to the comms. Turning on noclip and teleporting onto the bridge causes me to fall through the bridge. I tested quite a bit before setting a small vertical velocity to ensure I don't fall through the bridge. It seems to fix that problem for me.

jckhng is fine. Thank you so much for all the work on the VR mod!

**Comment by KozGit** [comment]
I'm back from vacation, sorry I couldn't respond sooner. Thanks for the new teleport mode!

**Comment by CarlKenner** [comment]
By the way, jckhng, I fixed that issue a different way, by actually teleporting to the exact final destination at the end of the warp. And I fixed the teleport time distortion not working when combined with your slow-mo motion sickness aid. And I fixed the time distortion not working in com_fixedTic and com_noSleep modes (which are necessary for performance).

**Comment by jckhng** [comment]
Hi @CarlKenner , that is definitely a better fix instead of adding a bump at the end. Thank you!

**Pull request merged**
