### PR TITLE
Remaining Player AAS files and crash fix

### PR DESCRIPTION
**Pull request by CarlKenner**

### CODE REVIEW

**Comment by CarlKenner** [comment]
Well, that's all the Player AAS files that the current code can generate without crashing.

**Comment by CarlKenner** [comment]
The Player AAS files take up **1.15 Gigabytes** in total!
I recommend telling users to use Windows' built in compressed folders feature on the map folder. It will shrink it down to 547 Megabytes. Ideally, they should be in a .pk4 zip file, but BFG edition removed support for them. They zip to 276 Megabytes.

On my computer, the aas_player files use unix LF line-breaks. But I think my git accidentally converts them to CR LF when I push them. Line breaks are a significant fraction of the file size, so we should convert them all to just LF before releasing.

I haven't checked how much memory they use while loaded, but it's probably quite significant. The AAS system wasn't really designed to include everywhere a player can reach.

On my computer, it takes an hour or two to build the larger map AAS files. Small maps only take a few minutes.

Teleporting will still work without any Player AAS files, but you'll be stuck only teleporting to and from places a zombie could go. And multiplayer maps don't have any AAS files originally.

I'm not sure what to do about the file size issue. I feel like 1.15 GB is too much.

We could possibly come up with a binary format, or we could reduce the precision (eg. round things to the nearest inch), if you think the files are too large.

**Comment by KozGit** [comment]
Are you worried about download size, or the on disk size?
( If it's download size, FWIW, people had no issue downloading  the 2.something gig file for the hd texture pack mod. )

How does not using the player .aas files and falling back to the zombie .aas realistically impact playability when teleporting?   I haven't looked at the AAS system in any depth yet, so I'm not exactly sure what that would mean to the player - I know some of the benefits from all the work you put in to them, I just don't know the full scope.

Making it an optional download sort of sounds good, but I'm worried we'll be fighting conflicting bug reports until the end of time if people are using different verisons.

**Comment by CarlKenner** [comment]
Download size should be OK, because it will be heavily compressed. It's more about disk space. Maybe I'm just behind the times though, and a Gigabyte is nothing these days.

In Mars City Underground, you can't teleport down the last flight of stairs in the crane area. There are also doors you can't teleport through. You can't teleport up or down the stairs in the area where you need to use the flashlight. And when you go out the airlock, you get stuck outside without any oxygen and can't teleport again until you get back inside and near the elevator door. On your way back, you get injured trying to teleport through the broken railing, because monsters don't like falling off ledges and prefer to take the long way through the fire.

And you can't teleport down from ledges unless they're really short, over railings, up onto secret areas, into small gaps, or anywhere you have to duck.

On the other hand, the zombie AAS files are better in some ways. The crates tend to be solid in the zombie AAS files, but not the player AAS files. But I hacked a non-AAS solution around that, so you can teleport onto and off crates that are within jump or fall height. There's also a bug in the player AAS file where you first get your weapon and armour. The landing at the top of the stairs has an area that it thinks is much higher than it really is. But my hack accidentally worked around that too.

I haven't really tested using the zombie AAS files for other levels. I haven't even tested the player AAS for most levels.

I guess we shouldn't make it optional unless people complain. 

I tried building the Alpha Labs 2 level again overnight last night (many hours), after reverting the player flood classes, but it still crashed on the last step. I guess I need to try not loading the .bproc files. If it still fails, that means the problem is the jump and fall height. Because those are the changes I made since I last successfully built the AAS file for that level.

If you want to see what the AAS system is doing, set ai_debugMove to 1. When checking for triggers and doors, we don't actually teleport along the green line though, we teleport along a series of the blue lines until we get stuck sometimes and then go in a straight line. I should probably improve the visualisation to draw our actual path. You can also use aas_showWallEdges 1 to see the nearby AAS walls.

**Pull request merged**
